name: Backup AEMET DB

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Iniciando backup automático..."

    - name: Descargar base de datos
      run: |
        curl -L -o aemet.db https://aemet-recolector.onrender.com/descargar-db

    - name: Crear carpeta y mover archivo
      run: |
        mkdir -p backups
        mv aemet.db "backups/aemet_$(date +'%Y-%m-%d_%H-%M').db"

    - name: Configurar Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Inicializar y subir archivo al repositorio
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git init
        git remote add origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
        git fetch origin main
        git checkout main
        git pull origin main
        git add backups/*.db
        git commit -m "Backup automático del $(date +'%Y-%m-%d %H:%M')"
        git push origin main

